// <auto-generated />
namespace doma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class m1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m1));
        
        string IMigrationMetadata.Id
        {
            get { return "201506120820311_m1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
