//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoSanPham()
        {
            this.ChiTietBoSanPham = new HashSet<ChiTietBoSanPham>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBoSanPham> ChiTietBoSanPham { get; set; }
    }
}
