//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int IDDonHang { get; set; }
        public int IDSanPham { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> IDBoSanPham { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public int ID { get; set; }
        public Nullable<double> DioGia { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual DonHang DonHang { get; set; }
    }
}
