//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBoSanPham
    {
        public int IDBoSanPham { get; set; }
        public int IDSanPham { get; set; }
        public int SoLuongThuongMua { get; set; }
        public string Size { get; set; }
    
        public virtual BoSanPham BoSanPham { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
