//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectS3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietBoSanPham = new HashSet<ChiTietBoSanPham>();
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public double DioGia { get; set; }
        public string linkanh { get; set; }
        public string MoTa { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Branches { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string UserUpdate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBoSanPham> ChiTietBoSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual ProductBranches ProductBranches { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
