//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoSanPham
    {
        public BoSanPham()
        {
            this.ChiTietBoSanPhams = new HashSet<ChiTietBoSanPham>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string Mota { get; set; }
    
        public virtual ICollection<ChiTietBoSanPham> ChiTietBoSanPhams { get; set; }
    }
}
