//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeadItem
    {
        public int id { get; set; }
        public string image { get; set; }
        public string caption { get; set; }
        public string href { get; set; }
        public int type { get; set; }
    }
}
